--- 
title: "Exploring different climate-smart methods and approaches"
author: "Tin Buenafe"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: tinbuenafe/SpatialPlanning
description: "This follows the spatial planning workflow to answer questions related to creating a holistic and flexible climate-smart marine spatial planning design."
---

# Background

This code follows the workflow of _SpatialPlanning_ repository. This project aims to create a holistic and flexible climate-smart marine spatial planning design using the Western Pacific as its template. To do this, we answer four key questions:

1. How much more would a climate-smart spatial design cost, compared to a climate-uninformed spatial design?
2. How does utilizing climate metrics calculated from different climatic variables change climate-smart spatial designs?
3. How can we incorporate climate metrics into a marine reserve design workflow?
4. What are the pros and cons of the different climate-smart marine reserve design approaches explored here?

All of these questions are explored here through a series of analyses. `prioritizr` is used here to create and solve spatial planning problems.

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')

# set working directory:
setwd("/Users/tinbuenafe/GitHub/SpatialPlanning/")
# call helper functions
source("SpatPlan_Extras.R") # Load the extras, including functions and libraries
source("SpatPlan_HelperFxns_WestPac.R") # Load helper functions written specifically for this spatial planning project
```
